### ISSUE TITLE
Check/correct updated German translation

### ISSUE THREAD

**Issue by aplaice** [axelboc/anki-ultimate-geography#229]
@Erim24 if you have time to look at these, at some point, please feel free to mercilessly tear them up — I made most of them with the thought that something is better than nothing.

I've listed the translations and summarised the reasons for the changes here, for ease of access, but it probably makes sense to continue the discussion in the relevant threads.

### Capital info mentioning The Hague (issue #218, pull request #228)

(Amsterdam is the official capital of the Netherlands (according to the constitution), but The Hague is the seat of the government, the legislature and the supreme court. (See [Capital of the Netherlands](https://en.wikipedia.org/wiki/Capital_of_the_Netherlands.))

For Tanzania, we do mention that:

> While Dodoma is the official capital, Dar es Salaam is the de facto seat of government.

)

Final English "Capital info":
While Amsterdam is the official capital, The Hague is the seat of the executive and legislative branches.
Merged German "Capital info":
Amsterdam ist die offizielle Hauptstadt, aber Den Haag ist der Parlaments- und Regierungssitz.

### Kaliningrad Oblast (issue #208)

Should the German also include a parenthesised explanation of what an oblast is in the country info? (Currently, it's "Oblast der Russischen Föderation.")

[Direct link to suggested update](https://github.com/axelboc/anki-ultimate-geography/issues/208#issuecomment-591128050).

Suggested updated English "Country info":
Oblast (region) of the Russian Federation.
Suggested updated German "Country info":
Oblast (Gebiet) der Russischen Föderation. (see [German Wikipedia](https://de.wikipedia.org/wiki/Oblast_Kaliningrad))

### Capital info for Canary Islands (issue #226)

(Make clear that Santa Cruz and Las Palmas are two different cities, since it otherwise sounds like it might be a single name...)

[Direct link to translation suggestion](https://github.com/axelboc/anki-ultimate-geography/issues/226#issuecomment-602224372).

Suggested English "Capital info":
The capital is shared between the two cities of Santa Cruz de Tenerife and Las Palmas
Suggested German "Capital info":
Die zwei städte Santa Cruz de Tenerife und Las Palmas de Gran Canaria sind zusammen Hauptstädte der (Autonomen Gemeinschaft der) Kanaren.

### Cetinje (issue #205)

According to the Montenegrin constitution, Cetinje is officially designated as the "Old Royal Capital" and is also the seat of the president. This information is now being added to the English "Capital info".

However, the relevant German Wikipedia articles, ([Montenegro](https://de.wikipedia.org/wiki/Montenegro), [Podgorica](https://de.wikipedia.org/wiki/Podgorica) and [Cetinje](https://de.wikipedia.org/wiki/Cetinje)) unlike the English, French and Spanish ones, do not appear to mention this special status of Cetinje, so I'm not sure whether to add this information.

Suggested English "Capital info" (WIP):
Podgorica is the capital; Cetinje is designated as the Old Royal Capital.
or perhaps just:
Cetinje is the Old Royal Capital.

Suggested German "Capital info":
Podgorica ist die Hauptstadt, aber Cetinje ist der Amtssitz des Präsidenten.

or (more comprehensive):
Alle wichtigen Institutionen des Montenegros haben ihren Sitz in Podgorica, mit Ausnahme des Staatspräsidenten, der in Cetinje residiert.
([basis](https://de.wikipedia.org/wiki/Podgorica))

### Capital of the EU (issue #213)

Suggested English "Capital info":
Brussels is the seat of the executive branch but the European Union has institutions in other European cities.
Suggested German "Capital info":
Brüssel ist der Sitz der Exekutive, aber es gibt auch Institutionen der Europäischen Union in anderen europäischen Städten.

**Comment by Erim24** [comment]
Hey @aplaice ,
I will have a look at it on the weekend.

**Comment by Erim24** [comment]
Hello @aplaice and all others as well,
I had a look at your suggestions. In general they are already quite good. However I suggest to change a few details. I also created a pull request (#238) addressing all these things: 

### Capital info for the Netherlands
Your suggestions sounds good. However, I  slightly rewrote it. In that way it sounds bit more like two statements that are connected. (Actually, it's mostly cosmetic ;) ):
`Amsterdam ist die offizielle Hauptstadt, **während** Den Haag Parlaments- und Regierungssitz **ist**.`

### Oblast Kaliningrad
as mentioned in my comment to issue [#208](#208) I would extend the info about the Oblast Kaliningrad to make clear that Oblast refers to an administrative unit:
`Oblast (**administratives** Gebiet) der Russischen Föderation.`

### Canary Islands
the thing with the Canary Islands is a bit more difficult. Your suggestion only had a typo:
`Die beiden **S**tädte Santa Cruz de Tenerife und Las Palmas de Gran Canaria sind zusammen die Hauptstädte der (Autonomen Gemeinschaft der) Kanaren.`
However, it sounds a bit weird but probably because it's not that common to have two capitals. Unfortunately none of the wikipedia articles about the Canary Islands or the capitals contains a better way.

### Cetinje
It would make sense to add the info you suggested, as it specifies where the president resides. However, as far as I can tell, that's not directly what the title of "Old Royal Capital" means.
If we want to add it I would suggest:
`Podgorica ist die Hauptstadt, während Cetinje Amtssitz des Präsidenten ist.`
That sounds a little smoother, in my opinion. However, I included it into my pull request, but I'm not sure if that would bloat the info in the deck. 

### Capital of EU
Here I have nothing to comment on. ;)

**Comment by aplaice** [comment]
Thanks very much for the comments, corrections and the pull request!

> However, as far as I can tell, that's not directly what the title of "Old Royal Capital" means.

The idea was that German Wikipedia did not seem to mention the special title/status of Cetinje (it mentioned that Cetinje once was the capital, but not that it currently has the constitutional status of "Old Royal Capital"), so arguably, the fact that it has this status is not notable for German-speakers (according to `anki-ultimate-geography`'s policy of following the respective language Wikipedias). The seat of the presidency is mentioned and is quite important, anyway, so I proposed adding that. However, I'm entirely confident with this logic, so it might be best just to use something along the lines of "Cetinje is an honorary capital.", in all the languages, including German.

**Comment by axelboc** [comment]
- [ ] Montenegro's honorary capital - discussing in #205 
- [x] Netherlands capital info - merged in #250 
- [x] Canary Islands capital info - merged in #233 
- [ ] Kaliningrad Oblast capital info - discussing in #208 
- [x] EU capital - merged in #245
