### ISSUE TITLE
Check/correct/update Norwegian translation

### ISSUE THREAD

**Issue by aplaice** [axelboc/anki-ultimate-geography#230]
@Vages if you have time to look at these, at some point, please feel free to mercilessly tear them up — I made most of them with the thought that something is better than nothing.

I've listed the translations and summarised the reasons for the changes, here, for ease of access, but it probably makes sense to continue the discussion in the relevant threads.

### Capital info mentioning the Hague (issue #218, pull request #228)

The English "Capital info" is now:
While Amsterdam is the official capital, The Hague is the seat of the executive and legislative branches.

I didn't change the Norwegian "Capital info", which was "Regjeringssete i Haag.". (I'm not sure if it's necessary to be more verbose.)

### Kaliningrad Oblast (issue #208)

Currently the Norwegian version is missing a "Country info" for Kaliningrad Oblast, to explain what Kaliningrad is.

[Direct link to suggested update](https://github.com/axelboc/anki-ultimate-geography/issues/208#issuecomment-591128050).

Suggested updated English "Country info":
Oblast (region) of the Russian Federation.
Suggested Norwegian "Country info":
Oblast (distrikt) i den russiske føderasjon.
(https://no.wikipedia.org/wiki/Kaliningrad_oblast)

### Capital info for Canary Islands (issue #226)

(Make clear that Santa Cruz and Las Palmas are two different cities, since it otherwise sounds like it might be a single name...)

[Direct link to translation suggestion](https://github.com/axelboc/anki-ultimate-geography/issues/226#issuecomment-602224372).

Suggested English "Capital info":
The capital is shared between the two cities of Santa Cruz de Tenerife and Las Palmas
Suggested Norwegian "Capital info":
De to byene Santa Cruz på Tenerife og Las Palmas på Gran Canaria deler hovedstadsstatusen.
(adapted from: https://no.wikipedia.org/wiki/Kanari%C3%B8yene)

### Cetinje (issue #205)

According to the Montenegrin constitution, Cetinje is officially designated as the "Old Royal Capital" and is also the seat of the president. This information is now being added to the English "Capital info".

I couldn't find this information in the relevant Norwegian Wikipedia articles (though that might be because my "reading" of Norwegian is basically just pattern-matching...), unlike in the English, French and Spanish ones, so it's not clear whether it should be included in the Norwegian version of the deck.

Suggested English "Capital info" (WIP):
Podgorica is the capital; Cetinje is designated as the Old Royal Capital.
or perhaps just:
Cetinje is the Old Royal Capital.

Suggested Norwegian "Capital info":
Podgorica er hovedstad, men presidenten holder til i den gamle hovedstaden Cetinje. ([basis](https://no.wikipedia.org/wiki/Montenegro#Politikk_og_administrasjon))

### Capital of the EU (issue #213)

In the [Norwegian article about the EU](https://no.wikipedia.org/wiki/Den_europeiske_union), three capitals are listed (Brussel, Strasbourg, Luxembourg) — should we use that?

Suggested English "Capital info":
Brussels is the seat of the executive branch but the European Union has institutions in other European cities.
Suggested Norwegian "Capital info":
Den europeiske unions institusjoner har hjemsteder i flere europeiske byer, inkludert Brussel (Europakommisjonen), Strasbourg (Europaparlamentet) og Luxembourg (Den europeiske unions domstol).

### "Capital info" for "Sahrawi Republic" (issue not yet filed)

Currently, the Norwegian version of the deck doesn't have a "capital info" mentioning that El Aaiún is only the official capital.

**Comment by axelboc** [comment]
@Vages, did you want to tweak the Norwegian capital info for the Netherlands? Personally, I think it's worth being more verbose for consistency, but up to you.

**Comment by axelboc** [comment]
- [ ] Netherlands capital info - see above
- [ ] Kaliningrad Oblast capital info - discussing in #208 
- [x] Canary Islands capital info - merged in #233 
- [ ] Montenegro's honorary capital - discussing in #205 
- [x] EU capital - merged in #245 
- [ ] SADR capital info - see #251

**Comment by Vages** [comment]
Yeah, being consistent is good. «Nasjonalforsamling og regjering i Haag» would be my suggestion. Should you or I fix this?

**Comment by axelboc** [comment]
Awesome! I'll do it, thanks for offering -- got plenty of time on my hands at the moment. 😉
